Repository encode/httpx, pull requests merged in 2019-12, with the labels that each got.

#569 Don't use background task in HTTP/1.1 dispatcher
  httpx/dispatch/http11.py
Labels: http/1.1, refactor

#599 Consistent suite of `stream_*` methods
  docs/api.md
  httpx/models.py
  tests/client/test_client.py
  tests/models/test_responses.py
Labels: user-experience

#594 Drop write_no_block from backends.
  httpx/concurrency/asyncio.py
  httpx/concurrency/base.py
  httpx/concurrency/trio.py
  httpx/dispatch/http2.py
Labels: concurrency

#596 Update changelog to include 'master'
  CHANGELOG.md
Labels: docs

#600 Add Client.stream() method.
  docs/compatibility.md
  docs/quickstart.md
  httpx/__init__.py
  httpx/api.py
  httpx/client.py
  tests/client/test_async_client.py
  tests/client/test_client.py
  tests/test_api.py
  tests/test_timeouts.py
Labels: enhancement

#601 Rename BaseSocketStream attributes on connections.
  httpx/dispatch/http11.py
  httpx/dispatch/http2.py
  httpx/dispatch/proxy_http.py
Labels: refactor

#603 Drop BackgroundManager in favor of fork(func1, func2)
  httpx/__init__.py
  httpx/concurrency/asyncio.py
  httpx/concurrency/auto.py
  httpx/concurrency/base.py
  httpx/concurrency/trio.py
  httpx/dispatch/http2.py
  tests/test_concurrency.py
Labels: concurrency

#597 Warn if cert / verify / trust_env are passed to client.request()
  docs/advanced.md
  docs/compatibility.md
  docs/environment_variables.md
  httpx/client.py
Labels: refactor

#611 Manadatory timeout argument on backend operations.
  httpx/concurrency/asyncio.py
  httpx/concurrency/trio.py
  tests/test_concurrency.py
Labels: refactor

#612 HTTP/2 refactoring
  httpx/dispatch/http2.py
Labels: http/2, refactor

#615 Refactor tests in the light of backend auto-detection
  tests/client/test_async_client.py
  tests/client/test_redirects.py
  tests/concurrency.py
  tests/conftest.py
  tests/dispatch/test_connection_pools.py
  tests/dispatch/test_connections.py
  tests/dispatch/test_http2.py
  tests/dispatch/test_proxy_http.py
  tests/dispatch/utils.py
  tests/test_concurrency.py
  tests/test_timeouts.py
Labels: concurrency, refactor, tooling

#616 Add OpenConnection base class
  httpx/dispatch/base.py
  httpx/dispatch/connection.py
  httpx/dispatch/http11.py
  httpx/dispatch/http2.py
Labels: refactor

#622 Tweak backport_start_tls implementation, and add 'nocover'.
  httpx/concurrency/asyncio.py
Labels: refactor

#625 Refactor `get_semaphore()`
  httpx/concurrency/asyncio.py
  httpx/concurrency/auto.py
  httpx/concurrency/base.py
  httpx/concurrency/trio.py
  httpx/dispatch/connection_pool.py
Labels: refactor

#626 Refactor BaseEvent
  httpx/concurrency/asyncio.py
  httpx/concurrency/base.py
  httpx/concurrency/trio.py
Labels: refactor

#628 Ensure H2 state is only accessed by the connection, not per-stream.
  httpx/dispatch/http2.py
Labels: http/2, refactor

#640 asyncio: Don't wait for the stream to close
  httpx/concurrency/asyncio.py
Labels: concurrency, http/2

#642 Force compiling 'regex' from source to resolve failing CI builds
  requirements.txt
Labels: bug, tooling

#645 No-I/O generator-based authentication flows
  httpx/auth.py
  httpx/client.py
Labels: refactor

#644 No I/O auth
  httpx/api.py
  httpx/auth.py
  httpx/client.py
  httpx/middleware.py
  httpx/models.py
  tests/client/test_auth.py
Labels: refactor

#649 Fix Host header and HSTS when the default port is in URL.
  httpx/client.py
  httpx/models.py
  tests/client/test_headers.py
  tests/models/test_url.py
Labels: bug

#653 `params=...` argument on URL should merge, not replace.
  httpx/models.py
  tests/models/test_url.py
Labels: bug

#658 Upgrade h11 to support both 0.8 and 0.9.
  setup.py
Labels: refactor

#660 Rationalize backend Semaphore interface slightly
  httpx/concurrency/asyncio.py
  httpx/concurrency/auto.py
  httpx/concurrency/base.py
  httpx/concurrency/trio.py
  httpx/dispatch/connection_pool.py
Labels: refactor

#648 Use Streams API for both requests and responses.
  httpx/client.py
  httpx/content.py
  httpx/content_streams.py
  httpx/dispatch/asgi.py
  httpx/dispatch/http11.py
  httpx/dispatch/http2.py
  httpx/dispatch/proxy_http.py
  httpx/models.py
  httpx/multipart.py
  httpx/utils.py
  tests/client/test_redirects.py
  tests/dispatch/test_http2.py
  tests/models/test_requests.py
  tests/models/test_responses.py
  tests/test_content_streams.py
  tests/test_decoders.py
  tests/test_multipart.py
Labels: refactor

#663 Remove httpxprof
  setup.cfg
  tools/httpxprof/.gitignore
  tools/httpxprof/README.md
  tools/httpxprof/httpxprof/__init__.py
  tools/httpxprof/httpxprof/__main__.py
  tools/httpxprof/httpxprof/config.py
  tools/httpxprof/httpxprof/main.py
  tools/httpxprof/httpxprof/scripts/__init__.py
  tools/httpxprof/httpxprof/scripts/async.py
  tools/httpxprof/httpxprof/scripts/sync.py
  tools/httpxprof/httpxprof/utils.py
  tools/httpxprof/setup.py
Labels: tooling

#666 Make 'request' non-optional on responses
  httpx/models.py
  tests/dispatch/test_http2.py
  tests/models/test_responses.py
  tests/test_decoders.py
  tests/test_multipart.py
Labels: user-experience

#664 Clean up 'backend' fixture
  tests/client/test_async_client.py
  tests/client/test_redirects.py
  tests/conftest.py
  tests/dispatch/test_connection_pools.py
  tests/dispatch/test_connections.py
  tests/dispatch/test_http2.py
  tests/dispatch/test_proxy_http.py
  tests/test_concurrency.py
  tests/test_timeouts.py
Labels: refactor, tooling

#673 Fix out-of-date streaming methods on Response API docs
  docs/api.md
Labels: docs

#677 Type-check test_cookies.py
  tests/client/test_cookies.py
Labels: tooling

#682 Gracefully end_stream early on no-body requests.
  httpx/dispatch/http2.py
Labels: bug, interop

#617 Drop per-request `cert`, `verify`, and `trust_env`
  httpx/client.py
  httpx/dispatch/asgi.py
  httpx/dispatch/base.py
  httpx/dispatch/connection.py
  httpx/dispatch/connection_pool.py
  httpx/dispatch/proxy_http.py
  tests/dispatch/test_connections.py
Labels: breaking, refactor

#674 Rename 'read/close' to 'aread/aclose' on Response
  docs/api.md
  docs/compatibility.md
  docs/quickstart.md
  httpx/client.py
  httpx/dispatch/proxy_http.py
  httpx/models.py
  tests/client/test_async_client.py
  tests/client/test_client.py
  tests/dispatch/test_connection_pools.py
  tests/dispatch/test_connections.py
  tests/dispatch/test_proxy_http.py
  tests/models/test_responses.py
  tests/test_api.py
  tests/test_decoders.py
Labels: breaking

#675 Rename 'close' to 'aclose' on Client
  docs/advanced.md
  docs/api.md
  httpx/client.py
Labels: breaking

#676 Rename 'next' to 'anext' on Response
  docs/api.md
  httpx/models.py
  tests/client/test_redirects.py
Labels: breaking

#680 Rename Client to AsyncClient (with compat synonym)
  docs/advanced.md
  docs/api.md
  docs/compatibility.md
  docs/environment_variables.md
  docs/http2.md
  httpx/__init__.py
  httpx/api.py
  httpx/client.py
  httpx/dispatch/asgi.py
  httpx/dispatch/base.py
  tests/client/test_async_client.py
  tests/client/test_auth.py
  tests/client/test_client.py
  tests/client/test_cookies.py
  tests/client/test_headers.py
  tests/client/test_properties.py
  tests/client/test_proxies.py
  tests/client/test_queryparams.py
  tests/client/test_redirects.py
  tests/dispatch/test_http2.py
  tests/test_asgi.py
  tests/test_multipart.py
  tests/test_timeouts.py
  tests/test_utils.py
Labels: docs, refactor

#693 Switch from an Event primitive to a Lock primitive
  httpx/backends/asyncio.py
  httpx/backends/auto.py
  httpx/backends/base.py
  httpx/backends/trio.py
  httpx/dispatch/http2.py
Labels: refactor

#691 Version 0.10.0
  CHANGELOG.md
  README.md
  docs/index.md
  httpx/__version__.py
Labels: docs

#699 Lock around `stream.write` and `stream.close` operations
  httpx/backends/asyncio.py
  httpx/backends/trio.py
Labels: bug

#700 Drop `OpenConnection`
  httpx/dispatch/base.py
  httpx/dispatch/connection.py
  httpx/dispatch/http11.py
  httpx/dispatch/http2.py
Labels: bug, refactor

#702 Drop unused `SSLConfig.with_overrides`
  httpx/config.py
Labels: refactor
