Repository encode/httpx, pull requests merged in 2019-09, with the labels that each got.

#153 Fix bug in calculating maximum frame size
  httpx/concurrency/base.py
  httpx/dispatch/http2.py
  tests/dispatch/test_http2.py
  tests/dispatch/utils.py
Labels: bug, http/2

#364 Add profiler tool
  noxfile.py
  setup.cfg
  tools/httpxprof/.gitignore
  tools/httpxprof/README.md
  tools/httpxprof/httpxprof/__init__.py
  tools/httpxprof/httpxprof/__main__.py
  tools/httpxprof/httpxprof/config.py
  tools/httpxprof/httpxprof/main.py
  tools/httpxprof/httpxprof/scripts/__init__.py
  tools/httpxprof/httpxprof/scripts/async.py
  tools/httpxprof/httpxprof/scripts/sync.py
  tools/httpxprof/httpxprof/utils.py
  tools/httpxprof/setup.py
Labels: perf

#307 Added support ssl cert file environment
  docs/environment_variables.md
  httpx/config.py
  httpx/utils.py
  tests/test_config.py
  tests/test_utils.py
Labels: help wanted
