Repository encode/httpx, pull requests merged in 2019-10, with the labels that each got.

#461 Fix some grammar in Advanced docs
  docs/advanced.md
Labels: hacktoberfest

#487 Document client block-usage and close()
  docs/advanced.md
  docs/api.md
  docs/compatibility.md
  docs/environment_variables.md
  docs/parallel.md
Labels: docs

#485 Drop proxies arg from the high level API
  docs/advanced.md
  docs/index.md
  httpx/api.py
Labels: proxies

#488 Document client-level configuration
  docs/advanced.md
Labels: docs

#484 Proposal: Make start_tls a method on streams & return a new stream
  httpx/concurrency/asyncio.py
  httpx/concurrency/base.py
  httpx/concurrency/trio.py
  httpx/dispatch/proxy_http.py
  tests/dispatch/utils.py
  tests/test_concurrency.py
Labels: tls+pki

#477 Change python 3.8-dev to python 3.8 in travis
  .travis.yml
Labels: tooling

#491 Reorganize timeout config tests
  tests/test_config.py
Labels: refactor
