Repository encode/httpx, pull requests merged in 2020-09, with the labels that each got.

#1240 Handle multiple auth headers correctly
  httpx/_auth.py
  tests/client/test_auth.py
Labels: bug

#1242 Minor test refactoring
  tests/test_asgi.py
Labels: refactor

#1241 Use sync client in test cases
  tests/test_multipart.py
Labels: refactor

#1243 Drop Response(..., request=...) style in test cases.
  tests/models/test_responses.py
  tests/test_decoders.py
Labels: refactor

#1247 Version 0.14.3
  CHANGELOG.md
  httpx/__version__.py
Labels: release

#1197 Issue warning on unclosed `AsyncClient`.
  httpx/_client.py
  tests/client/test_async_client.py
  tests/client/test_client.py
  tests/client/test_proxies.py
Labels: user-experience

#1248 Header refinements
  httpx/_client.py
  httpx/_models.py
  tests/client/test_headers.py
  tests/models/test_requests.py
Labels: enhancement

#1182 Drop urllib3 in favor of public gist
  README.md
  docs/advanced.md
  docs/compatibility.md
  docs/index.md
  docs/third-party-packages.md
  httpx/__init__.py
  httpx/_transports/urllib3.py
  scripts/coverage
Labels: breaking

#1260 Use shebang-style headers in environment variables docs
  docs/environment_variables.md
Labels: docs, refactor

#1257 Edited documentation about proxy-envs usage (#404)
  docs/environment_variables.md
Labels: docs

#1249 Drop `request.timer` attribute.
  httpx/_client.py
  httpx/_models.py
  httpx/_utils.py
  tests/models/test_responses.py
  tests/test_utils.py
Labels: refactor

#1217 Add support for sync-specific or async-specific auth flows
  docs/advanced.md
  httpx/_auth.py
  httpx/_client.py
  tests/client/test_auth.py
  tests/test_auth.py
Labels: enhancement

#1267 Swap auth/redirects ordering
  httpx/_client.py
  tests/client/test_redirects.py
Labels: bug

#1273 Switch auth/redirect methods to follow flow of execution better
  httpx/_client.py
Labels: refactor

#1272 Progress examples
  docs/advanced.md
  docs/img/rich-progress.gif
  docs/img/tqdm-progress.gif
Labels: docs

#1276 Minor decoder refactoring.
  httpx/_decoders.py
  httpx/_models.py
Labels: refactor

#1262 Update compatibility.md: mention differing query parameter handling
  docs/compatibility.md
Labels: docs

#1265 Support `Response(content=<bytes iterator>)`
  httpx/_content_streams.py
  httpx/_models.py
  httpx/_types.py
  tests/models/test_responses.py
  tests/test_content_streams.py
  tests/test_decoders.py
Labels: enhancement

#1282 Refactor to use `isinstance(..., typing.Iterator)`
  httpx/_content_streams.py
Labels: refactor

#1281 Refactor tests to use `MockTransport(<handler_function>)`
  requirements.txt
  tests/client/test_cookies.py
  tests/client/test_headers.py
  tests/client/test_queryparams.py
  tests/client/test_redirects.py
  tests/test_multipart.py
  tests/utils.py
Labels: refactor

#1288 Refactor test_auth.py to use `MockTransport` class.
  tests/client/test_auth.py
Labels: refactor

#1269 Drop chardet
  docs/quickstart.md
  httpx/_decoders.py
  httpx/_models.py
  setup.py
  tests/client/test_client.py
  tests/models/test_responses.py
  tests/test_decoders.py
Labels: enhancement

#1246 Event hooks
  docs/advanced.md
  httpx/_client.py
  tests/client/test_event_hooks.py
  tests/client/test_properties.py
Labels: enhancement

#1266 Seperate `content=...` and `data=...` parameters
  docs/compatibility.md
  docs/quickstart.md
  httpx/_api.py
  httpx/_client.py
  httpx/_content_streams.py
  httpx/_models.py
  httpx/_types.py
  tests/client/test_async_client.py
  tests/client/test_client.py
  tests/client/test_redirects.py
  tests/models/test_requests.py
  tests/test_api.py
  tests/test_asgi.py
  tests/test_content_streams.py
  tests/test_timeouts.py
  tests/test_wsgi.py
  tests/utils.py
Labels: user-experience

#1291 Update README.md
  README.md
  docs/index.md
Labels: docs

#1292 Refactor `encode` -> `encode_request`
  httpx/_content_streams.py
  httpx/_models.py
  tests/test_content_streams.py
  tests/test_multipart.py
Labels: refactor

#1293 Requests from transport API
  httpx/_models.py
  httpx/_types.py
  tests/utils.py
Labels: refactor

#1295 Drop ContentStream
  docs/exceptions.md
  httpx/__init__.py
  httpx/_auth.py
  httpx/_client.py
  httpx/_content_streams.py
  httpx/_exceptions.py
  httpx/_models.py
  httpx/_types.py
  tests/client/test_auth.py
  tests/client/test_redirects.py
  tests/models/test_requests.py
  tests/models/test_responses.py
  tests/test_content_streams.py
  tests/test_multipart.py
  tests/utils.py
Labels: refactor

#1296 Refactor content streams
  httpx/_content.py
  httpx/_content_streams.py
  httpx/_models.py
  httpx/_multipart.py
  httpx/_types.py
  tests/test_content.py
  tests/test_multipart.py
Labels: refactor

#1298 NetRC lookups should use host, not host+port
  httpx/_client.py
  httpx/_utils.py
Labels: bug

#1299 Neater `Host` header logic on redirects
  httpx/_client.py
Labels: refactor

#1297 Support Response(text=...), Response(html=...), Response(json=...)
  httpx/_content.py
  httpx/_models.py
  tests/client/test_auth.py
  tests/client/test_cookies.py
  tests/client/test_headers.py
  tests/client/test_queryparams.py
  tests/client/test_redirects.py
  tests/models/test_responses.py
Labels: enhancement

#1285 Finesse URL properties
  httpx/_auth.py
  httpx/_models.py
  setup.cfg
  tests/models/test_requests.py
  tests/models/test_url.py
Labels: enhancement, user-experience

#1301 Version 0.15.0
  CHANGELOG.md
  httpx/__init__.py
  httpx/__version__.py
  httpx/_client.py
  httpx/_config.py
  httpx/_models.py
  httpx/_transports/asgi.py
  httpx/_transports/wsgi.py
  setup.py
  tests/client/test_auth.py
  tests/client/test_client.py
  tests/client/test_event_hooks.py
  tests/client/test_redirects.py
  tests/models/test_headers.py
  tests/models/test_queryparams.py
  tests/test_config.py
  tests/test_timeouts.py
  tests/utils.py
Labels: release

#1306 Update docs for 0.15
  README.md
  docs/index.md
Labels: docs

#1307 Fix ASGITransport path escaping
  httpx/_transports/asgi.py
  tests/test_asgi.py
Labels: bug

#1312 Fix stream unsetting auth
  httpx/_client.py
  tests/client/test_auth.py
Labels: bug

#1313 Fix response.elapsed
  httpx/_client.py
Labels: bug

#1318 Release 0.15.3
  CHANGELOG.md
  httpx/__version__.py
Labels: release

#1322 Fix warning test case
  tests/client/test_auth.py
Labels: tooling

#1324 Fix automatic .read() when Response instances are created with content=<str>
  httpx/_models.py
  tests/models/test_responses.py
Labels: bug

#1326 Support header comparisons with dict or list.
  httpx/_models.py
  tests/models/test_headers.py
  tests/models/test_requests.py
  tests/models/test_responses.py
Labels: user-experience

#1327 Version 0.15.4
  CHANGELOG.md
  httpx/__version__.py
Labels: release
