Repository encode/httpx, pull requests merged in 2020-11, with the labels that each got.

#1386 Fix typo
  README.md
  docs/async.md
  docs/index.md
Labels: docs

#1389 Drop NBSP characters
  httpx/_models.py
  httpx/_status_codes.py
Labels: refactor

#1390 Use relative links for interlinking markdown files in docs
  docs/advanced.md
  docs/compatibility.md
  docs/environment_variables.md
  docs/third-party-packages.md
Labels: docs

#1391 WSGI 'PATH_INFO' should be URL unquoted
  httpx/_transports/wsgi.py
Labels: bug

#1362 Add support for Mount API
  docs/advanced.md
  httpx/_client.py
  tests/client/test_async_client.py
  tests/client/test_client.py
  tests/client/test_proxies.py
Labels: enhancement

#1277 Support for `chunk_size`
  httpx/_decoders.py
  httpx/_models.py
  tests/models/test_responses.py
  tests/test_decoders.py
Labels: enhancement

#1398 Add keepalive_expiry to Limits config
  httpx/_client.py
  httpx/_config.py
  tests/test_config.py
Labels: enhancement
