Repository encode/httpx, pull requests merged in 2020-04, with the labels that each got.

#804 Httpcore interface
  httpx/__init__.py
  httpx/__version__.py
  httpx/_client.py
  httpx/_config.py
  httpx/_content_streams.py
  httpx/_dispatch/asgi.py
  httpx/_dispatch/base.py
  httpx/_dispatch/connection.py
  httpx/_dispatch/connection_pool.py
  httpx/_dispatch/http11.py
  httpx/_dispatch/http2.py
  httpx/_dispatch/proxy_http.py
  httpx/_dispatch/urllib3.py
  httpx/_dispatch/wsgi.py
  httpx/_exceptions.py
  httpx/_models.py
  setup.cfg
  setup.py
  tests/client/test_async_client.py
  tests/client/test_auth.py
  tests/client/test_cookies.py
  tests/client/test_headers.py
  tests/client/test_proxies.py
  tests/client/test_queryparams.py
  tests/client/test_redirects.py
  tests/conftest.py
  tests/dispatch/__init__.py
  tests/dispatch/test_connection_pools.py
  tests/dispatch/test_connections.py
  tests/dispatch/test_http2.py
  tests/dispatch/test_proxy_http.py
  tests/dispatch/utils.py
  tests/test_concurrency.py
  tests/test_multipart.py
  tests/test_utils.py
Labels: refactor

#901 Drop concurrency backends
  httpx/_backends/__init__.py
  httpx/_backends/asyncio.py
  httpx/_backends/auto.py
  httpx/_backends/base.py
  httpx/_backends/trio.py
  tests/test_concurrency.py
Labels: refactor

#857 Implement streaming multipart uploads
  httpx/_content_streams.py
  httpx/_utils.py
  tests/test_multipart.py
Labels: enhancement, perf

#902 Move types definitions to a dedicated module
  httpx/_api.py
  httpx/_auth.py
  httpx/_client.py
  httpx/_config.py
  httpx/_content_streams.py
  httpx/_dispatch/urllib3.py
  httpx/_models.py
  httpx/_types.py
  httpx/_utils.py
Labels: refactor

#906 Avoid hasattr in hot loop in brotli decoder
  httpx/_decoders.py
Labels: perf
