Repository encode/httpx, pull requests merged in 2020-03, with the labels that each got.

#836 Revamp docs on Client instances
  docs/advanced.md
Labels: docs

#835 Enable NO_PROXY environment variable support
  httpx/_client.py
  tests/client/test_proxies.py
Labels: enhancement, proxies

#849 Version 0.12
  CHANGELOG.md
Labels: docs

#865 Fix type checking breakage
  httpx/_content_streams.py
Labels: bug, tooling

#823 Add docs on request instances to Requests compatibility guide
  docs/compatibility.md
Labels: docs

#876 Add 'Third Party Packages' docs page
  README.md
  docs/index.md
  docs/third-party-packages.md
  mkdocs.yml
Labels: docs

#883 Fix Client Docstring and add AsyncClient to API docs
  docs/api.md
  httpx/_client.py
Labels: docs

#882 Drop usage of `AnyStr`
  httpx/_content_streams.py
  httpx/_models.py
  httpx/_types.py
  httpx/_utils.py
Labels: refactor

#888 Remove stitches in `requirements.txt`
  requirements.txt
Labels: tooling

#889 Fix casing nits
  README.md
  httpx/_exceptions.py
Labels: docs

#886 Improve type hinting for `HTTPError.request`
  httpx/_client.py
  httpx/_exceptions.py
Labels: user-experience

#880 Add issue templates
  .github/ISSUE_TEMPLATE/1-question.md
  .github/ISSUE_TEMPLATE/2-bug-report.md
  .github/ISSUE_TEMPLATE/3-feature-request.md
Labels: tooling
