Repository encode/httpx, pull requests merged in 2020-07, with the labels that each got.

#1055 Add missing `Response.next()`
  httpx/_models.py
  tests/client/test_redirects.py
Labels: bug

#1054 Type check tests
  httpx/_types.py
  scripts/check
  tests/client/test_async_client.py
  tests/client/test_auth.py
  tests/client/test_client.py
  tests/client/test_cookies.py
  tests/client/test_headers.py
  tests/client/test_properties.py
  tests/client/test_proxies.py
  tests/client/test_queryparams.py
  tests/client/test_redirects.py
  tests/conftest.py
  tests/test_api.py
  tests/test_config.py
  tests/test_content_streams.py
  tests/test_multipart.py
  tests/test_status_codes.py
Labels: tooling

#1046 Add "manual streaming mode" docs
  docs/async.md
Labels: docs

#1058 Drop deprecated proxies API
  httpx/_client.py
Labels: enhancement

#1060 Support QueryParams(None)
  httpx/_client.py
  httpx/_models.py
  httpx/_types.py
  tests/models/test_queryparams.py
Labels: enhancement, refactor

#1052 Use relative tests directory references
  tests/client/test_auth.py
  tests/common.py
  tests/fixtures/.netrc
  tests/test_utils.py
Labels: refactor, tooling

#997 Tighten public client methods
  httpx/_client.py
  tests/client/test_client.py
Labels: enhancement

#1069 Drop fullpath setter
  httpx/_models.py
  tests/models/test_url.py
Labels: refactor

#1071 client.netrc should be private
  httpx/_client.py
Labels: refactor

#1075 Fixes for LineDecoding
  httpx/_decoders.py
  tests/test_decoders.py
Labels: bug

#1070 Drop private Origin model
  docs/api.md
  httpx/_client.py
  httpx/_models.py
  httpx/_utils.py
  tests/models/test_url.py
  tests/test_utils.py
Labels: refactor

#1076 Refactor map_exceptions
  httpx/_client.py
  httpx/_exceptions.py
Labels: refactor

#1077 Include 'request' on TooManyRedirect and RequestBodyUnavailable
  httpx/_auth.py
  httpx/_client.py
Labels: enhancement

#1073 Drop `URL(allow_relative=bool)`
  httpx/_client.py
  httpx/_models.py
  httpx/_utils.py
  tests/client/test_async_client.py
  tests/client/test_client.py
  tests/models/test_requests.py
  tests/models/test_url.py
Labels: refactor

#1079 Parameterise invalid URL tests
  tests/client/test_async_client.py
  tests/client/test_client.py
Labels: refactor

#1086 Full coverage, with exception of URLLib3Transport
  scripts/coverage
  tests/client/test_async_client.py
  tests/client/test_client.py
Labels: refactor

#1087 Keep Proxy._build_auth_header as a private method
  httpx/_config.py
Labels: refactor

#1084 Tighten public API on auth classes
  httpx/_auth.py
Labels: refactor

#1090 Drop extraneous `proxy` argument on `URLLib3Transport`.
  httpx/_transports/urllib3.py
Labels: refactor

#1088 Single consistent name for status codes
  httpx/__init__.py
  httpx/_models.py
  httpx/_status_codes.py
  tests/test_status_codes.py
Labels: user-experience

#996 Included create_ssl_context function to create the same context with SSLConfig and serve as API
  docs/advanced.md
  httpx/__init__.py
  httpx/_client.py
  httpx/_config.py
  httpx/_transports/urllib3.py
  tests/test_config.py
Labels: enhancement

#1104 Ignore PermissionError in netrc_info()
  httpx/_utils.py
Labels: enhancement

#1098 URL matching
  httpx/_client.py
  httpx/_utils.py
  tests/client/test_proxies.py
  tests/test_utils.py
Labels: refactor

#1099 Add support for no-proxy configurations
  httpx/_client.py
  httpx/_types.py
  tests/client/test_proxies.py
Labels: enhancement

#1096 Use public API only from transports
  httpx/_transports/asgi.py
  httpx/_transports/wsgi.py
Labels: refactor

#1085 httpx.Timeout must include a default
  httpx/_config.py
  tests/test_config.py
  tests/test_timeouts.py
Labels: enhancement, user-experience

#1089 Consistent multidict methods
  httpx/_models.py
  tests/models/test_headers.py
  tests/models/test_queryparams.py
Labels: user-experience

#1095 Exception hierarchy
  httpx/__init__.py
  httpx/_auth.py
  httpx/_client.py
  httpx/_decoders.py
  httpx/_exceptions.py
  httpx/_models.py
  httpx/_utils.py
  tests/client/test_proxies.py
  tests/test_asgi.py
  tests/test_decoders.py
  tests/test_wsgi.py
Labels: user-experience
