Repository encode/httpx, pull requests merged in 2020-10, with the labels that each got.

#1334 Add `response.next_request`
  docs/api.md
  docs/compatibility.md
  httpx/_client.py
  httpx/_models.py
  tests/client/test_redirects.py
Labels: requests-compat

#1335 Version 0.15.5
  CHANGELOG.md
  httpx/__version__.py
Labels: release

#1346 Tighten client closed-state behaviour
  httpx/_client.py
  tests/client/test_async_client.py
  tests/client/test_client.py
Labels: user-experience

#1339 Drop `.next()`/`.anext()` in favour of `response.next_request`
  docs/exceptions.md
  httpx/__init__.py
  httpx/_client.py
  httpx/_exceptions.py
  httpx/_models.py
  tests/client/test_async_client.py
  tests/client/test_client.py
  tests/client/test_redirects.py
Labels: requests-compat

#1338 Preserve header casing
  httpx/_models.py
  httpx/_utils.py
  tests/client/test_client.py
Labels: enhancement

#1347 Version 0.16
  CHANGELOG.md
  README.md
  docs/index.md
  httpx/__version__.py
  setup.py
Labels: release

#1349 Correctly handle ipv6 addresses as a part of URL
  httpx/_models.py
  tests/models/test_url.py
Labels: bug

#1351 Force lowercase ASGI headers
  httpx/_transports/asgi.py
  tests/test_asgi.py
Labels: bug

#1354 Version 0.16.1
  CHANGELOG.md
  httpx/__version__.py
Labels: release

#1361 Close AsyncClient properly in `test_async_next_request`
  tests/client/test_redirects.py
Labels: refactor

#1367 Drop unecessary host="localhost" in https_server fixture to fix CI build
  tests/conftest.py
Labels: refactor
