Repository encode/httpx, pull requests merged in 2020-01, with the labels that each got.

#703 Drop non-functional `Request.cookies` property.
  httpx/models.py
Labels: user-experience

#705 Bump coverage
  httpx/client.py
  httpx/config.py
  httpx/dispatch/proxy_http.py
  httpx/models.py
  tests/client/test_redirects.py
  tests/dispatch/test_http2.py
  tests/dispatch/utils.py
  tests/models/test_responses.py
  tests/test_decoders.py
Labels: refactor

#701 Version 0.10.1
  CHANGELOG.md
  httpx/__version__.py
Labels: docs

#706 SSLConfig refactor
  httpx/config.py
  httpx/dispatch/connection.py
  httpx/dispatch/connection_pool.py
  httpx/dispatch/proxy_http.py
  tests/client/test_proxies.py
  tests/dispatch/test_connections.py
Labels: perf, refactor

#695 Sync streaming interface on responses
  httpx/content_streams.py
  httpx/models.py
  tests/models/test_responses.py
  tests/test_content_streams.py
Labels: enhancement

#711 More coverage improvements
  httpx/backends/auto.py
  httpx/utils.py
  tests/concurrency.py
  tests/dispatch/utils.py
  tests/test_decoders.py
Labels: refactor

#709 Load SSL Context on init
  httpx/config.py
  httpx/dispatch/connection.py
  tests/test_config.py
Labels: refactor, user-experience

#719 Fix typo in 'Redirection and History' docs
  docs/quickstart.md
Labels: docs

#690 Repurpose `RedirectBodyUnavailable` exception as `RequestBodyUnavailable`
  httpx/__init__.py
  httpx/client.py
  httpx/exceptions.py
  tests/client/test_redirects.py
Labels: refactor

#721 Release max_connections for keepalive connections when closing the connection pool
  httpx/dispatch/connection_pool.py
  tests/dispatch/test_connection_pools.py
Labels: bug, pooling

#710 Drop `run` and `run_in_threadpool`
  httpx/backends/asyncio.py
  httpx/backends/auto.py
  httpx/backends/base.py
  httpx/backends/trio.py
  tests/concurrency.py
  tests/conftest.py
  tests/dispatch/test_connection_pools.py
  tests/test_concurrency.py
Labels: refactor

#725 Dispatcher -> AsyncDispatcher
  httpx/client.py
  httpx/dispatch/asgi.py
  httpx/dispatch/base.py
  httpx/dispatch/connection.py
  httpx/dispatch/connection_pool.py
  httpx/models.py
  tests/client/test_auth.py
  tests/client/test_cookies.py
  tests/client/test_headers.py
  tests/client/test_queryparams.py
  tests/client/test_redirects.py
  tests/test_multipart.py
Labels: refactor

#707 Wrap network errors as HTTPX-specific exceptions
  httpx/backends/asyncio.py
  httpx/backends/trio.py
  httpx/exceptions.py
  httpx/utils.py
Labels: user-experience

#713 Prep for introducing SyncClient
  httpx/__init__.py
  httpx/client.py
  httpx/config.py
  httpx/decoders.py
  httpx/models.py
  tests/client/test_proxies.py
  tests/test_config.py
Labels: refactor

#732 Public Auth API
  docs/advanced.md
  httpx/__init__.py
  httpx/auth.py
  httpx/client.py
  httpx/exceptions.py
  httpx/models.py
  tests/client/test_auth.py
  tests/models/test_requests.py
Labels: enhancement

#733 proxies_to_dispatchers -> get_proxy_map
  httpx/client.py
Labels: refactor

#735 Reintroduce sync API.
  httpx/__init__.py
  httpx/api.py
  httpx/client.py
  httpx/config.py
  httpx/dispatch/__init__.py
  httpx/dispatch/asgi.py
  httpx/dispatch/base.py
  httpx/dispatch/urllib3.py
  httpx/dispatch/wsgi.py
  httpx/models.py
  setup.cfg
  setup.py
  tests/client/test_client.py
  tests/client/test_proxies.py
  tests/dispatch/test_proxy_http.py
  tests/models/test_requests.py
  tests/test_api.py
  tests/test_wsgi.py
Labels: breaking, enhancement

#712 Improve docstring for PoolLimits
  httpx/config.py
Labels: docs

#727 Proposed 0.11 docs
  README.md
  docs/advanced.md
  docs/api.md
  docs/async.md
  docs/compatibility.md
  docs/environment_variables.md
  docs/http2.md
  docs/index.md
  docs/quickstart.md
  mkdocs.yml
Labels: docs

#737 Version 0.11.0
  CHANGELOG.md
  httpx/__version__.py
  mkdocs.yml
  setup.py
Labels: docs

#744 Fix typo in 'Streaming responses' docs
  docs/async.md
Labels: docs

#751 Setup custom domain for docs site
  docs/CNAME
Labels: bug, docs

#758 Support both zlib and deflate encodings
  httpx/decoders.py
  tests/test_decoders.py
Labels: bug

#750 Add an async example to intro snippets
  README.md
  docs/index.md
Labels: docs, user-experience

#763 Fix urllib3 proxy instantiation
  httpx/dispatch/urllib3.py
Labels: bug

#766 Fix for streaming a redirect response body with allow_redirects=False
  httpx/client.py
  tests/client/test_redirects.py
Labels: bug

#774 Handle redirect with malformed Location headers missing host.
  httpx/client.py
  httpx/models.py
  tests/client/test_redirects.py
Labels: user-experience

#773 Version 0.11.1
  CHANGELOG.md
  httpx/__version__.py
Labels: docs

#780 Detect credentials in proxy URLs and create Proxy-authorization header
  docs/advanced.md
  httpx/config.py
  tests/test_config.py
Labels: bug

#788 Fix `httpx.Proxy(..., mode="FORWARD_ONLY")` configuration.
  httpx/config.py
Labels: bug

#785 Switch to private module names
  docs/environment_variables.md
  httpx/__init__.py
  httpx/_api.py
  httpx/_auth.py
  httpx/_backends/__init__.py
  httpx/_backends/asyncio.py
  httpx/_backends/auto.py
  httpx/_backends/base.py
  httpx/_backends/trio.py
  httpx/_client.py
  httpx/_config.py
  httpx/_content_streams.py
  httpx/_decoders.py
  httpx/_dispatch/__init__.py
  httpx/_dispatch/asgi.py
  httpx/_dispatch/base.py
  httpx/_dispatch/connection.py
  httpx/_dispatch/connection_pool.py
  httpx/_dispatch/http11.py
  httpx/_dispatch/http2.py
  httpx/_dispatch/proxy_http.py
  httpx/_dispatch/urllib3.py
  httpx/_dispatch/wsgi.py
  httpx/_exceptions.py
  httpx/_models.py
  httpx/_status_codes.py
  httpx/_utils.py
  tests/client/test_auth.py
  tests/client/test_cookies.py
  tests/client/test_headers.py
  tests/client/test_queryparams.py
  tests/client/test_redirects.py
  tests/dispatch/test_connection_pools.py
  tests/dispatch/test_connections.py
  tests/dispatch/test_proxy_http.py
  tests/dispatch/utils.py
  tests/models/test_responses.py
  tests/models/test_url.py
  tests/test_concurrency.py
  tests/test_config.py
  tests/test_content_streams.py
  tests/test_decoders.py
  tests/test_multipart.py
  tests/test_utils.py
  tests/utils.py
Labels: refactor
