Repository encode/httpx, pull requests merged in 2020-05, with the labels that each got.

#923 Mark `Response.json()` as returning `Any`
  httpx/_models.py
Labels: user-experience

#969 Update dependencies in docs
  README.md
  docs/advanced.md
  docs/index.md
Labels: docs

#973 Add note on streaming uploads
  docs/advanced.md
Labels: docs

#974 Fix bytes support in multipart uploads
  httpx/_content_streams.py
  tests/test_multipart.py
Labels: bug

#976 Improve typing support for the `files` parameter
  httpx/_types.py
Labels: user-experience

#975 Tighten up types in multipart upload implementation
  httpx/_content_streams.py
  setup.cfg
Labels: refactor

#982 Add 'http2' for Client
  httpx/_client.py
Labels: http/2

#989 Remove unused concurrency test utils
  tests/concurrency.py
Labels: refactor

#991 Add mypy config for tests directory
  setup.cfg
Labels: tooling

#995 Add "Content-Length: 0" on POST, PUT, PATCH if required.
  httpx/_models.py
  tests/client/test_client.py
Labels: bug

#1010 Replace remaining occurrences of dispatch with transport
  httpx/_models.py
  httpx/_transports/asgi.py
  httpx/_transports/wsgi.py
  tests/client/test_auth.py
  tests/client/test_cookies.py
  tests/client/test_headers.py
  tests/client/test_queryparams.py
  tests/client/test_redirects.py
  tests/test_multipart.py
  tests/test_timeouts.py
Labels: refactor

#1003 Increase test coverage, document Headers.copy(), misc cleanup
  docs/api.md
  tests/client/test_async_client.py
  tests/client/test_client.py
  tests/client/test_proxies.py
  tests/conftest.py
  tests/models/test_headers.py
  tests/models/test_url.py
Labels: refactor, tooling
