Repository encode/httpx, pull requests merged in 2020-08, with the labels that each got.

#1107 Drop the auto-prompting 'do you want to run scripts/lint now'
  scripts/test
Labels: tooling

#1109 Rename URLMatcher -> URLPattern
  httpx/_client.py
  httpx/_utils.py
  tests/client/test_proxies.py
  tests/test_utils.py
Labels: refactor

#1112 client.trust_env becomes read-only
  httpx/_client.py
Labels: refactor

#1111 Switch to more concise Timeout parameters
  docs/advanced.md
  httpx/_config.py
  tests/test_config.py
  tests/test_timeouts.py
Labels: user-experience

#1103 Cleaner no proxy support
  httpx/_client.py
  httpx/_utils.py
  tests/client/test_proxies.py
  tests/test_utils.py
Labels: enhancement, perf, refactor

#1119 Use get_list consistently
  httpx/_models.py
  tests/models/test_headers.py
  tests/models/test_queryparams.py
Labels: refactor

#1122 Setting `app=...` or `transport=...` should bypass environment proxies.
  httpx/_client.py
Labels: bug

#1123 Revamp proxies documentation
  docs/advanced.md
  docs/environment_variables.md
Labels: docs, proxies

#1124 Refine docs phrasing on proxy routing
  docs/advanced.md
Labels: docs, proxies

#1125 Keep HTTPError as a base class for .request() and .raise_for_status()
  httpx/_exceptions.py
Labels: enhancement

#1110 Drop HSTS Preloading
  README.md
  docs/index.md
  httpx/_client.py
  setup.cfg
  setup.py
  tests/client/test_client.py
Labels: breaking

#1129 Clean up keyword argument name, using URL.join(url=...), not URL.join(relative_url=...).
  httpx/_client.py
  httpx/_models.py
Labels: refactor

#1127 Raise warning if proxy key is eg. "all" instead of "all://".
  docs/advanced.md
  httpx/_utils.py
  tests/client/test_proxies.py
Labels: enhancement

#1130 Base URL improvements
  httpx/_client.py
  httpx/_models.py
  tests/client/test_client.py
  tests/client/test_properties.py
Labels: bug, enhancement

#1132 Note on differences in proxy keys vs. `requests`
  docs/compatibility.md
Labels: docs

#1128 Deprecate `URL.is_ssl`
  httpx/_models.py
  tests/client/test_client.py
Labels: refactor

#1138 Document exceptions
  docs/exceptions.md
  httpx/_exceptions.py
  mkdocs.yml
Labels: docs

#1156 Fix behaviour with multiple Set-Cookie headers
  httpx/_models.py
  tests/models/test_cookies.py
Labels: bug

#1157 Minor rfc3986 refactoring
  httpx/_models.py
Labels: refactor

#1152 Expand client docstrings
  docs/api.md
  httpx/_client.py
Labels: docs

#1164 Version 0.14.1
  CHANGELOG.md
  httpx/__version__.py
Labels: release

#1155 Set `__module__ = 'httpx'` on everything we expose via the public API.
  httpx/__init__.py
Labels: enhancement

#1170 Ignore transfer-encoding if content-length presents
  httpx/_models.py
  tests/models/test_requests.py
Labels: bug

#1165 Advanced transport docs, with "local_address=..." example.
  docs/advanced.md
Labels: docs

#1166 Include invalid url exception in docs
  docs/exceptions.md
Labels: docs

#1159 Handle URL quoting username and password components.
  httpx/_models.py
  tests/models/test_url.py
Labels: bug

#1186 Document Unix Domain Socket usage
  docs/advanced.md
Labels: docs

#1193 Drop redundant hasattr check
  httpx/_models.py
Labels: refactor

#1187 Docs: Use pycon for Python console code blocks
  README.md
  docs/advanced.md
  docs/api.md
  docs/async.md
  docs/index.md
  docs/quickstart.md
Labels: docs

#1199 Include underlying httpcore exception tracebacks
  httpx/_exceptions.py
Labels: user-experience

#1207 Version 0.14.2
  CHANGELOG.md
  httpx/__version__.py
Labels: release

#1229 Use and pin black 20
  httpx/_api.py
  httpx/_client.py
  httpx/_config.py
  requirements.txt
  tests/client/test_auth.py
  tests/models/test_responses.py
  tests/test_utils.py
Labels: tooling

#1219 Closing AsyncClient in all tests (#871)
  tests/client/test_auth.py
  tests/test_asgi.py
  tests/test_multipart.py
Labels: refactor
