Repository encode/httpx, pull requests merged in 2021-04, with the labels that each got.

#1573 Escalate the distinction between `data=...` and `content=...` to be stricter.
  docs/compatibility.md
  httpx/_content.py
  tests/client/test_auth.py
  tests/models/test_requests.py
  tests/test_content.py
Labels: user-experience

#1577 Drop StreamContextManager in favour of `contextlib.contextmanager`/`asynccontextmanager`
  README.md
  docs/index.md
  httpx/_api.py
  httpx/_client.py
  httpx/_compat.py
  setup.py
Labels: refactor

#1583 For non-streaming cases, populate `request.content` automatically.
  httpx/_exceptions.py
  httpx/_models.py
  tests/models/test_requests.py
Labels: user-experience

#1574 Deprecate per-request cookies
  docs/compatibility.md
  httpx/_api.py
  httpx/_client.py
  tests/client/test_cookies.py
Labels: user-experience

#1584 `httpx.ResponseClosed` -> `httpx.StreamClosed`
  docs/exceptions.md
  httpx/__init__.py
  httpx/_exceptions.py
  httpx/_models.py
  tests/models/test_responses.py
Labels: refactor

#1579 Make Request and Response picklable
  httpx/_content.py
  httpx/_models.py
  tests/models/test_requests.py
  tests/models/test_responses.py
Labels: enhancement

#1590 Differentiate between 'url.host' and 'url.raw_host'
  httpx/_models.py
  tests/models/test_url.py
Labels: user-experience

#1598 Tweak QueryParams implementation
  httpx/_models.py
  tests/models/test_queryparams.py
Labels: refactor

#1600 Immutable QueryParams
  httpx/_client.py
  httpx/_models.py
  httpx/_utils.py
  tests/models/test_queryparams.py
Labels: user-experience

#1601 Expand URL interface
  httpx/_models.py
  tests/models/test_url.py
Labels: enhancement

#1602 Code comments for URL model
  httpx/_models.py
Labels: refactor

#1603 Perform port normalization for `http`, `https`, `ws`, `wss`, and `ftp` schemes.
  httpx/_models.py
  tests/client/test_proxies.py
  tests/models/test_url.py
Labels: user-experience

#1605 Update brotli support to use the brotlicffi package
  README.md
  docs/index.md
  httpx/_decoders.py
  requirements.txt
  setup.py
  tests/models/test_responses.py
  tests/test_decoders.py
Labels: refactor

#1607 Stream tweak
  httpx/_client.py
  httpx/_models.py
Labels: refactor

#1613 Add missing `timeout=...` to top-level `httpx.stream()` function.
  httpx/_api.py
Labels: bug

#1606 Map `httpcore` transport close exceptions to `httpx` exceptions.
  httpx/_transports/default.py
Labels: user-experience

#1619 Prefer `Content-Length` over `Transfer-Encoding: chunked` for `content=<file-like>` cases.
  httpx/_content.py
  httpx/_multipart.py
  httpx/_utils.py
  tests/test_content.py
Labels: enhancement
