Repository encode/httpx, pull requests merged in 2021-06, with the labels that each got.

#1682 👷 Add Python 3.10 beta to the CI
  .github/workflows/test-suite.yml
  requirements.txt
  tests/conftest.py
Labels: enhancement, tooling

#1687 Treat warnings as errors
  httpx/_client.py
  httpx/_compat.py
  httpx/_config.py
  setup.cfg
  tests/test_multipart.py
Labels: tooling

#1690 Version 0.18.2
  CHANGELOG.md
  httpx/__version__.py
Labels: release

#1710 Allow passing additional pytest args to scripts/test
  docs/contributing.md
  scripts/test
Labels: tooling

#1720 check sys.version_info and ssl.OPENSSL_VERSION_INFO once
  httpx/_compat.py
Labels: refactor
