Repository encode/httpx, pull requests merged in 2021-09, with the labels that each got.

#1828 BUG: wsgi.error should be TextIO, not BytesIO in WSGI transport
  httpx/_transports/wsgi.py
  tests/test_wsgi.py
Labels: enhancement

#1808 Switch follow redirects default
  docs/compatibility.md
  docs/quickstart.md
  httpx/_api.py
  httpx/_client.py
  httpx/_models.py
  tests/client/test_event_hooks.py
  tests/client/test_redirects.py
  tests/test_utils.py
Labels: breaking

#1858 List 'click' and 'rich' in the project dependencies
  README.md
  docs/index.md
Labels: docs

#1860 Tidy up the formatting of HTTP/2 requests
  README.md
  docs/index.md
  httpx/_main.py
Labels: user-experience
