Repository encode/httpx, pull requests merged in 2021-02, with the labels that each got.

#1462 Add Changelog link to PyPI page
  setup.py
Labels: docs

#1469 Handle default ports in WSGITransport
  httpx/_transports/wsgi.py
  tests/test_wsgi.py
Labels: bug

#1447 Tweak `create_ssl_context` defaults.
  httpx/_config.py
Labels: breaking, user-experience

#1489 Fix docs syntax highlighting
  mkdocs.yml
Labels: bug, docs
