Repository encode/httpx, pull requests merged in 2023-04, with the labels that each got.

#2659 fix: NO_PROXY should support IPv4, IPv6 and localhost
  httpx/_utils.py
  tests/test_utils.py
Labels: bug

#2671 Fix optional percent encoding behaviour.
  httpx/_urlparse.py
  tests/test_urlparse.py
Labels: bug

#2675 Additional context in InvalidURL exceptions.
  httpx/_urlparse.py
  tests/test_urlparse.py
Labels: enhancement

#2683 Add httpx-sse to Third Party Packages
  docs/third_party_packages.md
Labels: docs
