Repository encode/httpx, pull requests merged in 2024-02, with the labels that each got.

#3050 Deprecate `app=...` in favor of explicit `WSGITransport`/`ASGITransport`.
  CHANGELOG.md
  docs/advanced/transports.md
  docs/async.md
  httpx/_client.py
  tests/test_asgi.py
  tests/test_wsgi.py
Labels: 1.0 proposal

#3080 Extensions docs
  docs/advanced/extensions.md
  mkdocs.yml
Labels: docs

#3081 Improve 'Custom transports' docs
  docs/advanced/transports.md
Labels: docs

#3106 Define and expose the API from the same place
  httpx/__init__.py
  httpx/_api.py
  httpx/_auth.py
  httpx/_client.py
  httpx/_config.py
  httpx/_content.py
  httpx/_exceptions.py
  httpx/_models.py
  httpx/_status_codes.py
  httpx/_transports/__init__.py
  httpx/_transports/asgi.py
  httpx/_transports/base.py
  httpx/_transports/default.py
  httpx/_transports/mock.py
  httpx/_transports/wsgi.py
  httpx/_types.py
  httpx/_urls.py
  pyproject.toml
Labels: refactor

#3122 Delete `README_chinese.md`
  README_chinese.md
Labels: docs
