Repository encode/httpx, pull requests merged in 2024-10, with the labels that each got.

#3022 Add `httpx.SSLContext` configuration.
  .github/CONTRIBUTING.md
  CHANGELOG.md
  docs/advanced/ssl.md
  docs/compatibility.md
  docs/environment_variables.md
  docs/logging.md
  httpx/__init__.py
  httpx/_api.py
  httpx/_client.py
  httpx/_config.py
  httpx/_main.py
  httpx/_transports/default.py
  httpx/_types.py
  httpx/_utils.py
  tests/conftest.py
  tests/test_config.py
  tests/test_utils.py
Labels: api change, 1.0 proposal

#3335 Drop overloaded usage of 'verify' and 'cert'.
  docs/advanced/ssl.md
  httpx/_client.py
  httpx/_compat.py
  httpx/_config.py
  httpx/_transports/default.py
  httpx/_types.py
  tests/test_config.py
  tests/test_utils.py
Labels: api change, 1.0 proposal

#3343 Drop `_compat.py` module.
  httpx/_compat.py
  httpx/_decoders.py
  pyproject.toml
Labels: refactor

#3345 Cleanup `response.elapsed` implementation.
  httpx/_client.py
  httpx/_utils.py
Labels: refactor

#3364 Concise URL instantiation.
  httpx/_models.py
Labels: refactor

#3366 Allow deprecated `verify=<...>` and `cert=<...>`.
  httpx/__init__.py
  httpx/_api.py
  httpx/_client.py
  httpx/_config.py
  httpx/_transports/default.py
Labels: user-experience

#3319 Introduce new `SSLContext` API & escalate deprecations.
  .github/CONTRIBUTING.md
  .github/workflows/test-suite.yml
  CHANGELOG.md
  docs/advanced/ssl.md
  docs/compatibility.md
  docs/environment_variables.md
  docs/logging.md
  httpx/__init__.py
  httpx/__version__.py
  httpx/_api.py
  httpx/_client.py
  httpx/_compat.py
  httpx/_config.py
  httpx/_content.py
  httpx/_decoders.py
  httpx/_main.py
  httpx/_transports/asgi.py
  httpx/_transports/default.py
  httpx/_types.py
  httpx/_urls.py
  httpx/_utils.py
  pyproject.toml
  tests/client/test_proxies.py
  tests/conftest.py
  tests/models/test_url.py
  tests/test_asgi.py
  tests/test_config.py
  tests/test_utils.py
  tests/test_wsgi.py
Labels: 1.0 proposal

#3371 Review URL percent escaping sets, from whatwg.
  httpx/_urlparse.py
  tests/models/test_url.py
Labels: user-experience

#3375 Cleanup unneccessary test case
  tests/client/test_auth.py
Labels: refactor

#3382 Move normalize header functions from _utils.py to _models.py
  httpx/_models.py
  httpx/_utils.py
Labels: refactor
